### ISSUE TITLE
cargo-bloat seems to get confused by proc macros?

### ISSUE THREAD

**Issue by thomcc** [RazrFalcon/cargo-bloat#22]
When trying to determine what dependencies are contributing to the size of https://github.com/mozilla/mentat/ (after cd tools/cli, for example), `cargo bloat --release` indicates that most of them are coming from `syn`. Filtering to the `mentat` crate gives zero results.

It seems to be finding the executable that implements a procedural macro (in this case for `failure_derive`).

Explicitly passing `--bin mentat_cli` causes it to report correct information.

**Comment by RazrFalcon** [comment]
Interesting. The problem is that it builds `deps/libfailure_derive-bf1f074fc759e69b.so`, and native/C libraries have a priority over executable. And I don't know what exactly are you building. All I have is a list of libraries and binaries that was build. 

I've added `deps` filtering by `cdylib` target and not by the file extension.

**Comment by RazrFalcon** [comment]
I've published a new version.
